/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grpc.GetUserInfoByIdRequest', null, global);
goog.exportSymbol('proto.grpc.GetUserInfoResponse', null, global);
goog.exportSymbol('proto.grpc.UserInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.GetUserInfoByIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.GetUserInfoByIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.GetUserInfoByIdRequest.displayName = 'proto.grpc.GetUserInfoByIdRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.GetUserInfoByIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.GetUserInfoByIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.GetUserInfoByIdRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc.GetUserInfoByIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: msg.getUid()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.grpc.GetUserInfoByIdRequest} The clone.
 */
proto.grpc.GetUserInfoByIdRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.grpc.GetUserInfoByIdRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.grpc.GetUserInfoByIdRequest.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.grpc.GetUserInfoByIdRequest.prototype.setUid = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.GetUserInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.GetUserInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.GetUserInfoResponse.displayName = 'proto.grpc.GetUserInfoResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.GetUserInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.GetUserInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.GetUserInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc.GetUserInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    user: (f = msg.getUser()) && proto.grpc.UserInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.grpc.GetUserInfoResponse} The clone.
 */
proto.grpc.GetUserInfoResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.grpc.GetUserInfoResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional UserInfo user = 1;
 * @return {proto.grpc.UserInfo}
 */
proto.grpc.GetUserInfoResponse.prototype.getUser = function() {
  return /** @type{proto.grpc.UserInfo} */ (
    jspb.Message.getWrapperField(this, proto.grpc.UserInfo, 1));
};


/** @param {proto.grpc.UserInfo|undefined} value  */
proto.grpc.GetUserInfoResponse.prototype.setUser = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.grpc.GetUserInfoResponse.prototype.clearUser = function() {
  this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.grpc.GetUserInfoResponse.prototype.hasUser = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.UserInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.UserInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.UserInfo.displayName = 'proto.grpc.UserInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.UserInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.UserInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.UserInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc.UserInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: msg.getUid(),
    uname: msg.getUname()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.grpc.UserInfo} The clone.
 */
proto.grpc.UserInfo.prototype.cloneMessage = function() {
  return /** @type {!proto.grpc.UserInfo} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string uid = 1;
 * @return {string}
 */
proto.grpc.UserInfo.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.grpc.UserInfo.prototype.setUid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string uname = 2;
 * @return {string}
 */
proto.grpc.UserInfo.prototype.getUname = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.grpc.UserInfo.prototype.setUname = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.grpc);
